# Generated by Django 5.2.7 on 2025-10-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.IntegerField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('expenseName', models.CharField(max_length=150)),
                ('expenseNote', models.CharField(blank=True, max_length=255, null=True)),
                ('expenseLength', models.IntegerField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('groupID', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('transactionNote', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transaction.category')),
                ('storeID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transaction.store')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='user.profile')),
            ],
        ),
    ]
