# Generated by Django 5.2.7 on 2025-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_expense_expensename_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseName',
            field=models.CharField(default='General', max_length=150),
        ),
    ]
