# Generated by Django 5.2.7 on 2026-01-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryBudget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
