export const images = {
    racunko: require('./assets/pictures/racunko.png'),
    home: require('./assets/icons/img.png'),
    profile: require('./assets/icons/profile.png'),
    shutter: require('./assets/icons/camera-click.png'),
    flipCamera: require('./assets/icons/camera-flip.png'),
    thumbnail: require('./assets/icons/thumbnail.png'),
    google: require('./assets/icons/google.png'),
    profileIconWhite: require('./assets/icons/profileIconWhite.png'),
    plus: require('./assets/icons/plus.png'),
    whitePlus: require('./assets/icons/whitePlus.png'),
    hrana: require('./assets/icons/nutrition.png'),
    rezije: require('./assets/icons/rezije.png'),
    prijevoz: require('./assets/icons/prijevoz.png'),
    kucanstvo: require('./assets/icons/kucanstvo.png'),
    ljubimci: require('./assets/icons/ljubimci.png'),
    obrazovanje: require('./assets/icons/obrazovanje.png'),
    roba: require('./assets/icons/roba.png'),
    telekomunikacije: require('./assets/icons/telekomunikacije.png'),
    zabava: require('./assets/icons/zabava.png'),
    putovanja: require('./assets/icons/putovanja.png'),
    zdravlje: require('./assets/icons/zdravlje.png'),
    poklon: require('./assets/icons/pokloni.png'),
    restorani: require('./assets/icons/restorani.png'),
    minus: require('./assets/icons/redminus.png'),
    bluePlus: require('./assets/icons/blueplus.png'),
}
