
import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    chatContainer: {
        flex: 1,
        padding: 16,
    },
    header: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    headerIconButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    placeholderText: {
        fontSize: 20,
        fontWeight: '600',
        color: '#374151',
        textAlign: 'center',
        marginTop: 16,
        marginBottom: 8,
    },
    placeholderSubtext: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
    },
    messagesList: {
        flex: 1,
    },
    messagesContainer: {
        flexGrow: 1,
        paddingVertical: 8,
    },
    historyListContainer: {
        paddingVertical: 8,
    },
    historyItem: {
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
        marginBottom: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        shadowColor: '#000000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.08,
        shadowRadius: 2,
        elevation: 2,
    },
    historyTextContainer: {
        flex: 1,
        marginRight: 8,
    },
    historyTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111827',
        marginBottom: 4,
    },
    historySubtitle: {
        fontSize: 14,
        color: '#6B7280',
    },
    historyTime: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    messageWrapper: {
        marginVertical: 4,
        paddingHorizontal: 8,
    },
    userMessage: {
        backgroundColor: '#3B82F6',
        color: '#FFFFFF',
        padding: 12,
        borderRadius: 16,
        borderBottomRightRadius: 4,
        maxWidth: '80%',
        alignSelf: 'flex-end',
        fontSize: 15,
        lineHeight: 20,
    },
    aiMessage: {
        backgroundColor: '#FFFFFF',
        color: '#1F2937',
        padding: 12,
        borderRadius: 16,
        borderBottomLeftRadius: 4,
        maxWidth: '85%',
        alignSelf: 'flex-start',
        fontSize: 15,
        lineHeight: 20,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    messageBubble: {
        padding: 12,
        borderRadius: 16,
        marginVertical: 6,
        maxWidth: '85%',
    },
    userBubble: {
        backgroundColor: '#3B82F6',
        alignSelf: 'flex-end',
        borderBottomRightRadius: 4,
    },
    botBubble: {
        backgroundColor: '#FFFFFF',
        alignSelf: 'flex-start',
        borderBottomLeftRadius: 4,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    messageText: {
        fontSize: 15,
        lineHeight: 20,
        color: '#1F2937',
    },
    userMessageText: {
        color: '#FFFFFF',
    },
    botMessageText: {
        color: '#1F2937',
    },
    messageTime: {
        marginTop: 4,
        fontSize: 12,
        color: '#6B7280',
        textAlign: 'right',
    },
    inputContainer: {
        flexDirection: 'row',
        padding: 16,
        alignItems: 'flex-end',
    },
    input: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 24,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 16,
        maxHeight: 100,
        marginRight: 12,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    sendButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#3B82F6',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
})
