import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    display:{
        flex:1,
        flexDirection:'column',
        justifyContent:'flex-start',
        width:'100%',
        height:'100%',
        backgroundColor:'#2563EB',
    },
    container: {
        width:'100%',
        height:'20%',
        flexDirection:'row',
        backgroundColor: '#2563EB',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingTop:85,
    },
    mainHeader:{
        fontSize:50,
        color:'#FFFFFF',
        fontWeight:'800',
    },
    mainContent: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderTopRightRadius:50,
        borderTopLeftRadius:50,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:2,
        elevation: 15,
        shadowOffset:{width:0, height:-4},
        backgroundColor:'white',
        height: '80%',
        paddingBottom: '8%',
    },
    progressBarContainer: {
        flexDirection:'row',
        width:'100%',
        height:'6%',
        marginTop:30,
        justifyContent:'center',
        alignItems: 'center',
    },
    profileProgressContainer: {
        width:'10%',
        height: "100%",
        justifyContent:'center',
        alignItems: 'center',
        backgroundColor: "#2563EB",
        borderRadius:25,

    },

    linkProgressContainer: {
        width:'25%',
        height:'16%',
        backgroundColor:'#2563EB',
    },
    profileIcon:{
        width:'80%',
        height:'80%',
    },
    expensesProgressContainer: {
        width:'10%',
        height: "100%",
        justifyContent:'center',
        alignItems: 'center',
        backgroundColor: "#2563EB",
        borderRadius:25,
    },
    euro:{
        color:'#FFFFFF',
        fontSize:30,
        fontWeight:'500',
    },
    profileTextContainer:{
        width:'100%',
        height:'20%',
        justifyContent:'center',
        marginTop:25,
        alignItems: 'center',
        flexDirection:'column',
    },
    mainProfileText:{
        width:'80%',
        height:'45%',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems: 'center',
    },
    profileText: {
        color:'black',
        fontSize:24,
        fontWeight:'700',
    },
    secondaryProfileText: {
        width:'80%',
        height:'45%',
        gap: 5,
    },
    detailText: {
        color:'gray',
        fontSize:11,
        marginTop:1,
    },

    plusButton: {
        backgroundColor:'white',
        borderRadius:25,
        width:'15%',
        height:'80%',
        justifyContent:'center',
        alignItems: 'center',
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:5,
        elevation:5,
        shadowOffset:{width:0, height:4},
    },
    plus:{
        width:'100%',
        height:'100%',
        backgroundColor:'white',
        borderRadius:25,
    },
    plusButton1: {
        backgroundColor:'gray',
        opacity: 0.5,
        borderRadius:25,
        width:'15%',
        height:'80%',
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:5,
        shadowOffset:{width:0, height:4},
        elevation:5,
        justifyContent:'center',
        alignItems: 'center',
    },
    modalScreen:{
        flex:1,
        justifyContent:'center',
        alignItems:"center",
    },
    modalBox:{
        width:'100%',
        height:'100%',
        flexDirection:"column",
        backgroundColor:'white',
        borderRadius:25,
        justifyContent:'flex-start',
        alignItems: 'center',
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:2,
        elevation:5,
        borderWidth: 2,
        borderColor:'#2563EB',
        shadowOffset:{width:0, height:4},
        overflow: "hidden",
    },
    modalHeader:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems: 'flex-end',
        width:'100%',
        height:'13%',
        backgroundColor: "#2563EB",
        borderTopRightRadius:25,
        borderTopLeftRadius:25,
    },
    modalHeaderText:{
        color:'#FFFFFF',
        fontSize:23,
        marginBottom:20,
        fontWeight:'600',
        marginLeft: 20,
    },
    modalBoxComponent:{
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems: 'center',
        gap:3,
        width:'100%',
        height:70,
        marginTop:5,
        borderBottomWidth:1,
        borderBottomColor:'#D9D9D9',
    },
    componentPictureBox:{
        width:'20%',
        height:'100%',
        marginLeft:5,
        justifyContent:'center',
        alignItems: 'center',
    },
    componentPicture:{
        width:'100%',
        height:'100%',
    },
    componentBox:{
        width:'70%',
        height:'100%',
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems: 'center',
    },
    componentName:{
        fontSize:17,
        color:'black',
    },
    closeButtonBox:{
        width:'15%',
        height:'40%',
        borderRadius:5,
        marginBottom:10,
        marginRight:20,
        backgroundColor:'#6a86f1',
        justifyContent:'center',
        alignItems: 'center',
    },
    closeButton:{
        fontSize: 23,
        color:'white',
    },
    categoryBox:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'70%',
        height:70,
        borderWidth:1,
        gap:5,
        borderColor:'lightgray',
        borderRadius:20,
    },
    categoryBoxContainer:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height:70,
        gap:10,
    },
    categoryImage:{
        width:'20%',
        height:'90%',
        borderRadius:25,
    },
    categoryName:{
        fontSize:17,
        color:'black',
    },
    rightSideInputBox:{
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
        flex: 1,
        height:'100%',
    },
    euro2: {
        color:'black',
        fontSize:17,
        fontWeight:'300',
        marginRight: 15,
    },
    input:{
        width:'70%',
        fontSize:17,
        fontWeight:'300',
        textAlign:'right',
    },
    minusContainer:{
        width:'10%',
        height:40,
        backgroundColor:'#f5f6f8',
        justifyContent:'center',
        alignItems: 'center',
        borderRadius:25,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:5,
        elevation:5,
        shadowOffset:{width:0, height:4},
    },
    minus:{
        width:'100%',
        height:'100%',
        borderRadius:25,
    },
    submit:{
        width:'30%',
        height:40,
        borderRadius:25,
        backgroundColor:'#2563EB',
        justifyContent:'center',
        alignItems: 'center',

    },
    submitText:{
        fontSize:17,
        color:'white',
    },
})