import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    display:{
        flex:1,
        flexDirection:'column',
        justifyContent:'flex-start',
        width:'100%',
        height:'100%',
        backgroundColor:'#2563EB',
    },
    container: {
        width:'100%',
        height:'20%',
        flexDirection:'row',
        backgroundColor: '#2563EB',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingTop:85,

    },
    mainHeader:{
        fontSize:50,
        color:'#FFFFFF',
        fontWeight:'800',
    },
    mainContent: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        borderTopRightRadius:50,
        borderTopLeftRadius:50,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:2,
        elevation: 15,
        shadowOffset:{width:0, height:-4},
        backgroundColor:'white',
        height: '80%',
        paddingBottom: '8%',
    },
    landingPageImgBox: {
        width: '100%',
        height:"50%",
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width:'75%',
        height: '100%',
    },
    textBox: {
        width: '100%',
        flexDirection:'column',
        justifyContent:'center',
        alignItems:'center',
        height:'15%',
        backgroundColor:'white',
        padding: 10,
    },
    text1: {
        color:'black',
        fontSize:30,
        fontWeight:'400',
    },
    text2: {
      color:'black',
      fontSize: 20,
      fontWeight:'300',
    },
    text3:{
        color:'white',
        fontSize:20,
        fontWeight:'700',
    },
    buttonBox:{
        width:'100%',
        height:'20%',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        gap:15,
        backgroundColor:'white',
    },
    registracija:{
        width:'42%',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        height:'50%',
        backgroundColor:'#1E40AF',
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    prijava:{
        width:'42%',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        height:'50%',
        backgroundColor:'#60A5FA',
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
});