import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    loginPage: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        borderTopRightRadius:50,
        borderTopLeftRadius:50,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowOffset:{width:0, height:-4},
        backgroundColor:'white',
        height: '80%',
        paddingBottom: '8%',
    },
    titleBox: {
        display: 'flex',
        flexDirection:'column',
        justifyContent:'flex-start',
        alignItems:'center',
        gap: 15,

    },
    title: {
        fontSize: 40,
    },
    secondaryTitle: {
        fontSize: 16,
        color: '#000000',
        opacity: 0.4,
    },
    thirdTitle: {
      fontSize: 10,
      color: '#000000',
      opacity: 0.4,
    },
    textInputBox: {
        width: '100%',
        height: '25%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        boxSizing: 'border-box',
        gap: 20,
    },
    textInputBorder: {
      width:'80%',
      height: '30%',
      display: 'flex',
      flexDirection:'column',
      alignItems:'flex-start',
      paddingHorizontal:10,
      paddingTop: 5,
      borderWidth: 1,
      borderColor:'#888',
      borderRadius: 15,
    },
    input: {
        boxSizing: 'border-box',
        width: '100%',
        flex: 1,
        color: 'black',
        height: '100%',
        placeholderTextColor: 'black',
    },
    textInputBorderPassword: {
        display: 'flex',
        flexDirection:'row',
        width: '80%',
        height: '30%',
        justifyContent:'space-between',
        paddingHorizontal:10,
        paddingTop: 5,
        borderWidth: 1,
        borderColor:'#888',
        borderRadius: 15,
    },
    passwordBox: {
        width: '90%',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    inputPassword: {
        flex: 1,
        color: '#000000',
        alignItems: 'center',
    },
    eyeBtn: {
        alignSelf: 'center',
    },
    buttonsContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-evenly',
        alignItems:'center',
        gap: 40,
    },
    button: {
        paddingHorizontal: 20,
        paddingVertical: 20,
        backgroundColor: '#2563EB',
        borderRadius: 25,
        width: '60%',
        alignItems: 'center',
    },
    text: {
        color:'white',
        fontSize:20,
    },
    separator: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '80%',
        alignItems: "center",
        gap: 20,
    },
    line: {
        width: '25%',
        height: '0%',
        borderWidth: 0.5,
        borderColor: '#000',
        opacity: 0.4,
    },
    googleButton: {
        paddingHorizontal: 20,
        paddingVertical: 20,
        backgroundColor: 'white',
        borderRadius: 25,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowOffset:{width:0, height:4},
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        width: '60%',
        gap: 20
    },
    googleText: {
        color: 'black',
        opacity: 0.5,
        fontSize: 16,

    },
    googleIcon: {
        width: 25,
        height: 25,
    },
});