import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    container: {
        width: '100%',
        height: '100%',
        justifyContent: 'flex-start',
        alignSelf: 'center',
        paddingVertical: 40,
        gap: 30,
    },
    transactionType: {
        width: '80%',
        alignSelf: 'center',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    buttonExpense: {
        backgroundColor: 'red',
        width: '45%',
        padding: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    buttonIncome: {
        backgroundColor: 'green',
        width: '45%',
        padding: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    buttonGray: {
        backgroundColor: 'gray',
        opacity: 0.5,
        width: '45%',
        padding: 15,
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    inputContainer: {
        display: 'flex',
        alignSelf: 'center',
        justifyContent: 'space-between',
        flexDirection: 'row',
        width: '80%',
        borderWidth: 1,
        borderColor: 'gray',
        paddingHorizontal: 15,
        paddingVertical: 20,
        borderRadius: 10,
    },
    amountWrap: {
        display: 'flex',
        flexDirection: "row",
        justifyContent: 'flex-end',
        flex: 1,
    },
    amount: {
        fontSize: 25,
        alignSelf: "center",
        height: '100%',
        flex: 1,
        textAlign: "right",
    },
    chooseCategory: {
      display: 'flex',
      flexDirection: 'row',
      flex: 1,
      justifyContent: 'flex-end',
    },
    text: {
        fontSize: 18,
        color: '#2563EB',
        alignSelf: 'center',
    },
    text2: {
        fontSize: 16,
        flex: 1,
        textAlign: 'right',
    },
    text3: {
        fontSize: 20,
        color: 'white',
        textAlign: 'center',
        fontWeight: 'bold',
    },
    text4: {
        color: 'white',
        fontSize: 20,
        textAlign: 'center',
    },

    buttonContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-end',
        flex: 1,
    },
    button: {
        display: 'flex',
        width: '50%',
        justifyContent: 'center',
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: 'gray',
        paddingHorizontal: 15,
        paddingVertical: 15,
        borderRadius: 10,
        backgroundColor: '#2563EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
});