import {StyleSheet, Text} from 'react-native';
import React from "react";

export default StyleSheet.create({
    display:{
        flex:1,
        flexDirection:'column',
        justifyContent:'flex-start',
        width:'100%',
        height:'100%',
        backgroundColor:'#2563EB',
    },
    container: {
        width:'100%',
        height:'20%',
        flexDirection:'row',
        backgroundColor: '#2563EB',
        justifyContent: 'center',
        alignItems: 'flex-start',
        paddingTop:85,
    },
    mainHeader:{
        fontSize:50,
        color:'#FFFFFF',
        fontWeight:'800',
    },
    mainContent: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'flex-start',
        borderTopRightRadius:50,
        borderTopLeftRadius:50,
        shadowColor:'#3e3d3d',
        shadowOpacity:0.7,
        shadowRadius:2,
        elevation: 15,
        shadowOffset:{width:0, height:-4},
        backgroundColor:'white',
        height: '80%',
        paddingBottom: '8%',
    },
    progressBarContainer: {
        flexDirection:'row',
        width:'100%',
        height:'6%',
        marginTop:30,
        justifyContent:'center',
        alignItems: 'center',
    },
    profileProgressContainer: {
        width:'10%',
        height: "100%",
        justifyContent:'center',
        alignItems: 'center',
        backgroundColor: "#2563EB",
        borderRadius:25,

    },

    linkProgressContainer: {
      width:'25%',
      height:'16%',
      backgroundColor:'#D9D9D9',
    },
    profileIcon:{
        width:'80%',
        height:'80%',
    },
    expensesProgressContainer: {
        width:'10%',
        height: "100%",
        justifyContent:'center',
        alignItems: 'center',
        backgroundColor: "#D9D9D9",
        borderRadius:25,
    },
    euro:{
        color:'#FFFFFF',
        fontSize:30,
        fontWeight:'500',
    },
    profileTextContainer:{
        width:'100%',
        height:'20%',
        justifyContent:'center',
        marginTop:25,
        alignItems: 'center',
        flexDirection:'column',
    },
    mainProfileText:{
        width:'80%',
        height:'35%',
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems: 'center',
    },
    profileText: {
        color:'black',
        fontSize:24,
        fontWeight:'700',
    },
    secondaryProfileText: {
        width:'80%',
        height:'45%',
        gap: 5,
    },
    detailText: {
        color:'gray',
        fontSize:11,
    },
    inputContainer:{
        flexDirection:'column',
        justifyContent:'flex-start',
        alignItems:'center',
        gap:25,
        width:'100%',
        height:'40%',
    },
    inputBox:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:'80%',
        height:'25%',
        borderWidth:1,
        borderColor:'lightgray',
        borderRadius:20,
    },
    incomeText:{
        color:'#2563EB',
        fontSize:20,
        fontWeight:'300',
        marginLeft:15,
    },
    rightSideInputBox:{
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
        gap:3,
        width:'50%',
        height:'100%',
    },
    input:{
        width:'70%',
        fontSize:20,
        fontWeight:'300',
        textAlign:'right',
    },
    euro2: {
        color:'black',
        fontSize:20,
        fontWeight:'300',
        marginRight: 15,
    },
    switchBox: {
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'35%',
        height:'50%',
    },
    dateBox: {
        flexDirection:'row',
        width:'50%',
        height:'100%',
        justifyContent:'center',
        alignItems:'center',
    },
    buttonText:{
        fontSize:20,
    },
    picker: {
        justifyContent:'center',
        width:'100%',
        fontSize:15,
        textAlign:'right',
        borderRadius:25,
    },
    footerTextBox:{
        flexDirection: 'row',
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height:'10%',
        bottom: "2%"
    },
    footerText:{
        color:'gray',
        fontSize:11,
    },
    continueButton:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height:'15%',
    },
    continueButtonBox:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        width:'40%',
        height:'50%',
        backgroundColor:'#2563EB',
        borderRadius:25,
    },
    continue:{
        color:'white',
        fontSize:25,
        fontWeight:'300',
    }

})