# Generated by Django 5.2.7 on 2025-10-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=255)),
                ('groupCode', models.CharField(max_length=150, unique=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('role', models.CharField(max_length=150)),
                ('isAdmin', models.BooleanField(default=False)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('income', models.IntegerField(blank=True, null=True)),
                ('allowance', models.IntegerField(blank=True, null=True)),
                ('groupName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.group')),
            ],
        ),
    ]
