# Generated by Django 5.2.7 on 2025-10-30 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_income_date_profile_wants_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wants_notification',
            new_name='notifications',
        ),
        migrations.AlterField(
            model_name='profile',
            name='income_date',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{2}$', 'Date must be formatted as DD-MM format')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='User', max_length=150),
        ),
    ]
