# Generated by Django 5.2.7 on 2025-11-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_wants_notification_profile_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
