# Generated by Django 5.2.7 on 2025-12-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isUser',
            field=models.BooleanField(default=True),
        ),
    ]
