# Generated by Django 5.2.7 on 2026-01-05 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_message_isuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
